sudo: required

language: python
python:
  - "2.7"

services:
  - docker

env:
  global:
  - DOCKER_VERSION=1.11.2-0~trusty
  - DOCKER_COMPOSE_VERSION=1.6.0

before_install:
  - apt-cache madison docker-engine
  - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-engine=${DOCKER_VERSION}
  - docker version
  - docker info
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats

install: "pip install -e ."
script: cd tests; bats tests