sudo: required

language: python
python:
  - "2.7"

services:
  - docker

before_install:
  - apt-cache madison docker-engine
  #- apt-get -o Dpkg::Options::="--force-confnew" install -y docker-engine=${DOCKER_VERSION}
  - docker --version
  - docker info
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats

install: "pip install -e ."
script: cd tests; bats tests