sudo: required

language: python
python:
  - "2.7"

services:
  - docker

before_install:
  - docker info
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats

install: "pip install -r requirements.txt"
script: bats ./tests/tests