version: '2.1'

services:
  nginx:
    image: iamdork/nginx-proxy
    build: ../nginx
    labels:
    - org.iamdork.auxiliary
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - /etc/nginx/vhost.d
    - /usr/share/nginx/html
    - /etc/nginx/conf.d
    - ${DORK_PROXY_AUTH_DIR}:/etc/nginx/htpasswd:ro
    - ${DORK_PROXY_CERTS_DIR}:/etc/nginx/certs:ro

  dockergen:
    image: iamdork/dockergen
    build: ../dockergen
    userns_mode: host
    privileged: true
    labels:
    - org.iamdork.auxiliary
    volumes_from:
    - nginx
    volumes:
    - ${DOCKER_SOCK}:/tmp/docker.sock:ro
    - ../dockergen/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl
    command: -notify-sighup dork_aux_proxy_nginx_1 -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    environment:
      HTTPS_METHOD: ${DORK_PROXY_HTTPS_METHOD}

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    labels:
    - org.iamdork.auxiliary
    volumes_from:
    - nginx
    volumes:
    - /etc/nginx/certs
    - ${DOCKER_SOCK}:/var/run/docker.sock:ro
