version: '2.1'
services:
  vault:
    image: vault:0.6.2
    labels:
    - org.iamdork.auxiliary
    privileged: true
    userns_mode: host
    cap_add:
    - IPC_LOCK
    ports:
    - 8200:8200
    environment:
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
      VAULT_DEV_ROOT_TOKEN_ID: 'dork'
