version: '2'
services:
  vault:
    image: vault
    labels:
    - org.iamdork.auxiliary
    ports:
    - 8200:8200
    environment:
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
      VAULT_DEV_ROOT_TOKEN_ID: 'dork'
