import dork_compose.plugin
import platform
import pkg_resources
from subprocess import call
import tempfile
import os


class Plugin(dork_compose.plugin.Plugin):

    def environment(self):
        return {
            'DORK_DNS_PORT': "53",
            'DORK_PROXY_DOMAIN': "dork",
        }

    @property
    def auxiliary_project(self):
        return pkg_resources.resource_filename('dork_compose', 'auxiliary/dns')

    def initializing(self, project, service_names=None):
        if platform.system() == "Darwin":
            resolver = '/etc/resolver/%s' % self.env.get('DORK_PROXY_DOMAIN')
            print "Root password required to update DNS settings."
            if not os.path.isfile(resolver):
                content = "# Generated by dork-composer\nnameserver 127.0.0.1\nport %s" % (
                    self.environment()['DORK_DNS_PORT']
                )
                tmp = tempfile.NamedTemporaryFile(delete=False)
                tmp.write(content)
                tmp.close()
                call(['sudo', 'cp', tmp.name, resolver])
                call(['sudo', 'chmod', '664', resolver])
                os.remove(tmp.name)
            call(['sudo', 'dscacheutil', '-flushcache'])
            call(['sudo', 'killall', '-HUP', 'mDNSResponder'])

        if platform.system() == "Linux":
            resolver = '/etc/resolv.conf'
            confline = 'nameserver 127.0.0.1'

            lines = []
            with open(resolver, 'r') as resolvconf:
                for line in resolvconf.readlines():
                    if confline in line:
                        return
                    lines.append(line)

            lines.append(confline + '\n')
            lines.append('\n')
            tmp = tempfile.NamedTemporaryFile(delete=False)
            tmp.write(''.join(lines))
            tmp.close()
            print "Root password required to update DNS settings."
            call(['sudo', 'cp', tmp.name, resolver])
            call(['sudo', 'chmod', '664', resolver])
            os.remove(tmp.name)
