version: '2'

services:
  dns:
    image: andyshinn/dnsmasq:2.75
    cap_add:
    - NET_ADMIN
    ports:
    - ${DORK_DNS_PORT}:53/tcp
    - ${DORK_DNS_PORT}:53/udp
    command: -A /${DORK_PROXY_DOMAIN}/127.0.0.1