version: '2'

services:
  front:
    image: jwilder/nginx-proxy
    labels:
    - org.iamdork.proxy
    volumes:
    - ${DOCKER_SOCK}:/tmp/docker.sock:ro
    - ${DORK_PROXY_AUTH_DIR}:/etc/nginx/htpasswd:ro
    environment:
    - DORK_PROXY_SKIP
    ports:
    - "80:80"
    - "443:443"
